from nft_splitbrain.core import (
    STATUS_ALTERNATIVES_MISMATCH,
    STATUS_CANNOT_VERIFY_HIDDEN_RULES,
    STATUS_HIDDEN_LEGACY_RULES,
    STATUS_HIDDEN_NFT_RULES,
    STATUS_NO_BACKEND_FOUND,
    STATUS_OK,
    count_ruleset_lines,
    diagnose,
    diagnose_host,
    get_alternatives_mode,
    get_reported_mode,
    which,
)


def test_get_reported_mode_nft():
    def fake_runner(cmd, timeout=15):
        return "iptables v1.8.11 (nf_tables)\n"

    assert get_reported_mode("iptables", runner=fake_runner) == "nft"


def test_get_reported_mode_legacy():
    def fake_runner(cmd, timeout=15):
        return "iptables v1.8.11 (legacy)\n"

    assert get_reported_mode("iptables", runner=fake_runner) == "legacy"


def test_get_reported_mode_none_when_unparseable():
    def fake_runner(cmd, timeout=15):
        return "some garbage output"

    assert get_reported_mode("iptables", runner=fake_runner) is None


def test_get_alternatives_mode_nft():
    sample = (
        "iptables - auto mode\n"
        "  link best version is /usr/sbin/iptables-nft\n"
        "  link currently points to /usr/sbin/iptables-nft\n"
    )

    def fake_runner(cmd, timeout=15):
        return sample

    assert get_alternatives_mode("iptables", runner=fake_runner) == "nft"


def test_get_alternatives_mode_legacy():
    sample = "  link currently points to /usr/sbin/iptables-legacy\n"

    def fake_runner(cmd, timeout=15):
        return sample

    assert get_alternatives_mode("iptables", runner=fake_runner) == "legacy"


def test_get_alternatives_mode_none_when_no_alternatives_system():
    def fake_runner(cmd, timeout=15):
        return "update-alternatives: error: no alternatives for iptables"

    assert get_alternatives_mode("iptables", runner=fake_runner) is None


def test_which_true():
    def fake_runner(cmd, timeout=15):
        return "/usr/sbin/iptables\n"

    assert which("iptables", runner=fake_runner) is True


def test_which_false():
    def fake_runner(cmd, timeout=15):
        return ""

    assert which("iptables", runner=fake_runner) is False


def test_count_ruleset_lines_skips_comments_and_blank():
    sample = "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\n\n-A INPUT -j ACCEPT\nCOMMIT\n"

    def fake_runner(cmd, timeout=15):
        return sample, "", 0

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert count == 4
    assert permission_denied is False


def test_count_ruleset_lines_detects_permission_denied():
    def fake_runner(cmd, timeout=15):
        return "", "iptables-legacy-save: Permission denied (you must be root)\n", 1

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert count is None
    assert permission_denied is True


def test_count_ruleset_lines_nonzero_exit_without_permission_text_not_flagged():
    def fake_runner(cmd, timeout=15):
        return "", "some other unrelated error\n", 1

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert permission_denied is False


def test_diagnose_no_backend_found():
    report = diagnose(
        iptables_available=False, nft_available=False,
        reported_mode=None, alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_NO_BACKEND_FOUND


def test_diagnose_alternatives_mismatch():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="legacy", alternatives_mode="nft",
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_ALTERNATIVES_MISMATCH
    assert report.details


def test_diagnose_hidden_legacy_rules():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=12, nft_rule_lines=None,
    )
    assert report.status == STATUS_HIDDEN_LEGACY_RULES


def test_diagnose_hidden_nft_rules():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="legacy", alternatives_mode="legacy",
        legacy_rule_lines=None, nft_rule_lines=5,
    )
    assert report.status == STATUS_HIDDEN_NFT_RULES


def test_diagnose_ok_when_consistent_and_clean():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=0, nft_rule_lines=None,
    )
    assert report.status == STATUS_OK


def test_diagnose_ok_with_no_alternatives_system_and_consistent():
    report = diagnose(
        iptables_available=True, nft_available=False,
        reported_mode="nft", alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_OK


def test_report_to_dict_roundtrip():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="legacy",
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    d = report.to_dict()
    assert d["status"] == STATUS_ALTERNATIVES_MISMATCH
    assert d["reported_mode"] == "nft"
    assert d["alternatives_mode"] == "legacy"


def test_diagnose_host_integration():
    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (nf_tables)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-nft\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["iptables-legacy-save"]:
            return "# Generated\n", "", 0
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_OK
    assert report.legacy_rule_lines == 0


def test_diagnose_host_integration_permission_denied_surfaces_cannot_verify():
    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (nf_tables)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-nft\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["iptables-legacy-save"]:
            return "", "iptables-legacy-save v1.8.11: Permission denied (you must be root)\n", 4
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_CANNOT_VERIFY_HIDDEN_RULES
    assert report.permission_denied is True
    assert report.legacy_rule_lines is None


def test_diagnose_permission_denied_not_reported_as_ok():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=None, nft_rule_lines=None,
        legacy_permission_denied=True,
    )
    assert report.status == STATUS_CANNOT_VERIFY_HIDDEN_RULES
    assert report.status != STATUS_OK
