from nft_splitbrain.core import (
    STATUS_ALTERNATIVES_MISMATCH,
    STATUS_CANNOT_VERIFY_HIDDEN_RULES,
    STATUS_HIDDEN_LEGACY_RULES,
    STATUS_HIDDEN_NFT_RULES,
    STATUS_NFT_ONLY_NO_IPTABLES,
    STATUS_NO_BACKEND_FOUND,
    STATUS_OK,
    STATUS_UNDETERMINED_MODE,
    count_ruleset_lines,
    diagnose,
    diagnose_host,
    get_alternatives_mode,
    get_reported_mode,
    which,
)


def test_get_reported_mode_nft():
    def fake_runner(cmd, timeout=15):
        return "iptables v1.8.11 (nf_tables)\n"

    assert get_reported_mode("iptables", runner=fake_runner) == "nft"


def test_get_reported_mode_legacy():
    def fake_runner(cmd, timeout=15):
        return "iptables v1.8.11 (legacy)\n"

    assert get_reported_mode("iptables", runner=fake_runner) == "legacy"


def test_get_reported_mode_none_when_unparseable():
    def fake_runner(cmd, timeout=15):
        return "some garbage output"

    assert get_reported_mode("iptables", runner=fake_runner) is None


def test_get_alternatives_mode_nft():
    sample = (
        "iptables - auto mode\n"
        "  link best version is /usr/sbin/iptables-nft\n"
        "  link currently points to /usr/sbin/iptables-nft\n"
    )

    def fake_runner(cmd, timeout=15):
        return sample

    assert get_alternatives_mode("iptables", runner=fake_runner) == "nft"


def test_get_alternatives_mode_legacy():
    sample = "  link currently points to /usr/sbin/iptables-legacy\n"

    def fake_runner(cmd, timeout=15):
        return sample

    assert get_alternatives_mode("iptables", runner=fake_runner) == "legacy"


def test_get_alternatives_mode_none_when_no_alternatives_system():
    def fake_runner(cmd, timeout=15):
        return "update-alternatives: error: no alternatives for iptables"

    assert get_alternatives_mode("iptables", runner=fake_runner) is None


def test_which_true():
    def fake_runner(cmd, timeout=15):
        return "/usr/sbin/iptables\n"

    assert which("iptables", runner=fake_runner) is True


def test_which_false():
    def fake_runner(cmd, timeout=15):
        return ""

    assert which("iptables", runner=fake_runner) is False


def test_count_ruleset_lines_skips_comments_and_blank():
    sample = "# Generated by iptables-save\n*filter\n:INPUT ACCEPT\n\n-A INPUT -j ACCEPT\nCOMMIT\n"

    def fake_runner(cmd, timeout=15):
        return sample, "", 0

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert count == 4
    assert permission_denied is False


def test_count_ruleset_lines_detects_permission_denied():
    def fake_runner(cmd, timeout=15):
        return "", "iptables-legacy-save: Permission denied (you must be root)\n", 1

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert count is None
    assert permission_denied is True


def test_count_ruleset_lines_nonzero_exit_without_permission_text_not_flagged():
    def fake_runner(cmd, timeout=15):
        return "", "some other unrelated error\n", 1

    count, permission_denied = count_ruleset_lines(["iptables-legacy-save"], runner=fake_runner)
    assert permission_denied is False


def test_count_ruleset_lines_execution_failure_not_silently_zero():
    """Regression: run_capture() returns ("", "", None) when the underlying
    command fails to even execute (binary vanished between the `which`
    check and this call, or the subprocess timed out) -- see
    test_core_run_helper.test_run_capture_missing_binary_returns_none_code
    and the timeout test. Previously count_ruleset_lines only recognized
    an execution failure when stderr matched a permission-denied phrase;
    a returncode of None with empty stderr fell through to count=0,
    permission_denied=False -- indistinguishable from 'the other backend
    genuinely holds zero rules'. diagnose_host() would then report a false
    STATUS_OK ('no hidden rules found') on a host it never actually
    checked, instead of the honest 'cannot verify' state."""

    def fake_runner(cmd, timeout=15):
        return "", "", None

    count, could_not_verify = count_ruleset_lines(["nft", "list", "ruleset"], runner=fake_runner)
    assert count is None
    assert could_not_verify is True


def test_diagnose_no_backend_found():
    report = diagnose(
        iptables_available=False, nft_available=False,
        reported_mode=None, alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_NO_BACKEND_FOUND


def test_diagnose_nft_only_host_is_clean_not_undetermined():
    """Regression: a fully-migrated nftables-only host (no iptables binary
    at all, only 'nft') has no second inspection command that could ever
    disagree with nftables -- split-brain is not possible by definition.
    Previously this fell through to STATUS_UNDETERMINED_MODE (exit code 2,
    'has NOT been verified clean'), a false positive on an increasingly
    common, genuinely clean configuration on modern minimal distros."""
    report = diagnose(
        iptables_available=False, nft_available=True,
        reported_mode=None, alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_NFT_ONLY_NO_IPTABLES
    assert report.status != STATUS_UNDETERMINED_MODE


def test_diagnose_undetermined_mode_does_not_silently_report_ok():
    """Regression: when neither --version self-report nor
    update-alternatives can determine the active backend, the tool must
    not fall through to a false STATUS_OK even though hidden rule lines
    were actually found in the legacy backend -- it genuinely can't tell
    which backend is active, so it must say so rather than claim clean."""
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode=None, alternatives_mode=None,
        legacy_rule_lines=5, nft_rule_lines=None,
    )
    assert report.status == STATUS_UNDETERMINED_MODE
    assert report.status != STATUS_OK


def test_diagnose_undetermined_mode_even_with_no_rule_lines():
    report = diagnose(
        iptables_available=True, nft_available=False,
        reported_mode=None, alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_UNDETERMINED_MODE


def test_diagnose_alternatives_mismatch():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="legacy", alternatives_mode="nft",
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_ALTERNATIVES_MISMATCH
    assert report.details


def test_diagnose_hidden_legacy_rules():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=12, nft_rule_lines=None,
    )
    assert report.status == STATUS_HIDDEN_LEGACY_RULES


def test_diagnose_hidden_nft_rules():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="legacy", alternatives_mode="legacy",
        legacy_rule_lines=None, nft_rule_lines=5,
    )
    assert report.status == STATUS_HIDDEN_NFT_RULES


def test_diagnose_ok_when_consistent_and_clean():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=0, nft_rule_lines=None,
    )
    assert report.status == STATUS_OK


def test_diagnose_ok_with_no_alternatives_system_and_consistent():
    report = diagnose(
        iptables_available=True, nft_available=False,
        reported_mode="nft", alternatives_mode=None,
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    assert report.status == STATUS_OK


def test_report_to_dict_roundtrip():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="legacy",
        legacy_rule_lines=None, nft_rule_lines=None,
    )
    d = report.to_dict()
    assert d["status"] == STATUS_ALTERNATIVES_MISMATCH
    assert d["reported_mode"] == "nft"
    assert d["alternatives_mode"] == "legacy"


def test_diagnose_host_integration():
    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (nf_tables)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-nft\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["iptables-legacy-save"]:
            return "# Generated\n", "", 0
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_OK
    assert report.legacy_rule_lines == 0


def test_diagnose_host_integration_permission_denied_surfaces_cannot_verify():
    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (nf_tables)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-nft\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["iptables-legacy-save"]:
            return "", "iptables-legacy-save v1.8.11: Permission denied (you must be root)\n", 4
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_CANNOT_VERIFY_HIDDEN_RULES
    assert report.permission_denied is True
    assert report.legacy_rule_lines is None


def test_diagnose_host_integration_legacy_active_checks_nft_ruleset():
    """Mirror of test_diagnose_host_integration for the active_mode == "legacy"
    branch: when iptables-legacy is the active backend, diagnose_host must
    check `nft list ruleset` for hidden nft rules (core.py's
    `if active_mode == "legacy" and nft_available:` branch). Before this
    test, only the active_mode == "nft" mirror (checking iptables-legacy-save)
    was ever exercised end-to-end -- a bug in this branch's wiring (wrong
    variable, wrong command, wrong permission flag threaded through) would
    have gone undetected."""

    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (legacy)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-legacy\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["nft", "list", "ruleset"]:
            return "# Warning: table ip filter is managed by iptables-nft\n", "", 0
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_OK
    assert report.reported_mode == "legacy"
    assert report.nft_rule_lines == 0
    assert report.legacy_rule_lines is None


def test_diagnose_host_integration_legacy_active_hidden_nft_permission_denied():
    """Same active_mode == "legacy" branch, but nft list ruleset fails with a
    permission error -- must surface STATUS_CANNOT_VERIFY_HIDDEN_RULES with
    nft_permission_denied wired through, not silently report OK/empty."""

    def fake_runner(cmd, timeout=15):
        if cmd[0] == "which":
            return "/usr/sbin/" + cmd[1] + "\n"
        if cmd == ["iptables", "--version"]:
            return "iptables v1.8.11 (legacy)\n"
        if cmd == ["update-alternatives", "--display", "iptables"]:
            return "  link currently points to /usr/sbin/iptables-legacy\n"
        return ""

    def fake_capture_runner(cmd, timeout=15):
        if cmd == ["nft", "list", "ruleset"]:
            return "", "Operation not permitted\n", 1
        return "", "", 0

    report = diagnose_host(runner=fake_runner, capture_runner=fake_capture_runner)
    assert report.status == STATUS_CANNOT_VERIFY_HIDDEN_RULES
    assert report.permission_denied is True
    assert report.nft_rule_lines is None


def test_diagnose_permission_denied_not_reported_as_ok():
    report = diagnose(
        iptables_available=True, nft_available=True,
        reported_mode="nft", alternatives_mode="nft",
        legacy_rule_lines=None, nft_rule_lines=None,
        legacy_permission_denied=True,
    )
    assert report.status == STATUS_CANNOT_VERIFY_HIDDEN_RULES
    assert report.status != STATUS_OK
